package com.fbee.smarthome_wl.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.fbee.smarthome_wl.greendao.User;
import com.fbee.smarthome_wl.greendao.Doorlockrecord;
import com.fbee.smarthome_wl.greendao.Icon;

import com.fbee.smarthome_wl.greendao.UserDao;
import com.fbee.smarthome_wl.greendao.DoorlockrecordDao;
import com.fbee.smarthome_wl.greendao.IconDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig doorlockrecordDaoConfig;
    private final DaoConfig iconDaoConfig;

    private final UserDao userDao;
    private final DoorlockrecordDao doorlockrecordDao;
    private final IconDao iconDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        doorlockrecordDaoConfig = daoConfigMap.get(DoorlockrecordDao.class).clone();
        doorlockrecordDaoConfig.initIdentityScope(type);

        iconDaoConfig = daoConfigMap.get(IconDao.class).clone();
        iconDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        doorlockrecordDao = new DoorlockrecordDao(doorlockrecordDaoConfig, this);
        iconDao = new IconDao(iconDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Doorlockrecord.class, doorlockrecordDao);
        registerDao(Icon.class, iconDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        doorlockrecordDaoConfig.getIdentityScope().clear();
        iconDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public DoorlockrecordDao getDoorlockrecordDao() {
        return doorlockrecordDao;
    }

    public IconDao getIconDao() {
        return iconDao;
    }

}
