package com.fbee.smarthome_wl.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ICON.
 */
public class Icon {

    private Long id;
    private Integer typeid;
    private Integer type;
    private String name;
    private String imageurl;
    private Integer imageres;
    private String account;
    private String gateway;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Icon() {
    }

    public Icon(Long id) {
        this.id = id;
    }

    public Icon(Long id, Integer typeid, Integer type, String name, String imageurl, Integer imageres, String account, String gateway) {
        this.id = id;
        this.typeid = typeid;
        this.type = type;
        this.name = name;
        this.imageurl = imageurl;
        this.imageres = imageres;
        this.account = account;
        this.gateway = gateway;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTypeid() {
        return typeid;
    }

    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImageurl() {
        return imageurl;
    }

    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    public Integer getImageres() {
        return imageres;
    }

    public void setImageres(Integer imageres) {
        this.imageres = imageres;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getGateway() {
        return gateway;
    }

    public void setGateway(String gateway) {
        this.gateway = gateway;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
