package com.fbee.smarthome_wl.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER.
 */
public class User {

    private long userid;
    private int deviceid;
    private String useralias;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public User() {
    }

    public User(long userid) {
        this.userid = userid;
    }

    public User(long userid, int deviceid, String useralias) {
        this.userid = userid;
        this.deviceid = deviceid;
        this.useralias = useralias;
    }

    public long getUserid() {
        return userid;
    }

    public void setUserid(long userid) {
        this.userid = userid;
    }

    public int getDeviceid() {
        return deviceid;
    }

    public void setDeviceid(int deviceid) {
        this.deviceid = deviceid;
    }

    public String getUseralias() {
        return useralias;
    }

    public void setUseralias(String useralias) {
        this.useralias = useralias;
    }

    @Override
    public String toString() {
        return "User{" +
                "userid=" + userid +
                ", deviceid=" + deviceid +
                ", useralias='" + useralias + '\'' +
                '}';
    }
    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
